version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3030:3030"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend  # Le frontend doit attendre le backend
    restart: always

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:3.6  # Ancienne version compatible avec Mongoose 3.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
