apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dispatchr-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo 27017; do echo waiting for mongo...; sleep 2; done;']
      containers:
      - name: backend
        image: molka1405/dispatchr_cms-version1-backend:latest
        ports:
        - containerPort: 3030
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          value: "mongodb://mongo/dispatchr_cms"
        - name: REDIS_URL
          value: "redis://redis:6379"
        readinessProbe:
          httpGet:
            path: /
            port: 3030
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3030
          initialDelaySeconds: 15
          periodSeconds: 10
