apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dispatchr-cms

spec:
  type: LoadBalancer  
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # Port du service dans le cluster
      targetPort: 80    # Port d'écoute dans le container
